# Generated by Django 5.2.1 on 2025-05-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
