# Generated by Django 5.2.1 on 2025-05-23 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carro_unique_together_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.producto'),
        ),
    ]
